### ISSUE TITLE
Connection reached timeout

### ISSUE THREAD

**Issue by navisluni** [Azure/azure-remote-rendering-asset-tool#134]
Using the latest version of ARRT (2.3.6) when I try to start the session I get the following error:
SESSION: Connection reached timeout (10 sec). Session ID:  "XXXXXXXX"

Both ARR and Storage connection checks are correct.

Detailed log output:
![image](https://user-images.githubusercontent.com/29777939/173812587-68d56ac8-a8b4-400e-81f6-38039817480a.png)

**Comment by XcessPak** [comment]
[XCESSPAK-MAIN.07-25-2022.19-17-14.etl.zip](https://github.com/Azure/azure-remote-rendering-asset-tool/files/9181965/XCESSPAK-MAIN.07-25-2022.19-17-14.etl.zip)
mine also connection reached timeout kindly solve this problem
