### ISSUE TITLE
e57 Point Cloud rendering navigation is not feasible

### ISSUE THREAD

**Issue by travis-rothbloom** [Azure/azure-remote-rendering-asset-tool#144]
I've uploaded a small sample e57 point cloud and converted it in the ARRT using the option and without using the option to relocate the origin to center. Below is a video that displays what I see regardless of what option I use. The dimensions that the warning dialog that appears upon loading of the asset are accurate, and there's far under 10 million points in this cloud. I've highlighted each component in the tree and pressed F, as well as adjusted all the camera settings, but I can't find a way to orient around the asset that doesn't look like this below. I know this feature is still in beta, but can you please assist?

Alternatively, is there a sample e57 that I can try to replicate viewing on my computer?

https://arupnam-my.sharepoint.com/:v:/g/personal/travis_rothbloom_arup_com/EYgJJAJqe05Flu418jpkc6ABPQhTpy5s4hLmbcxqqYJywg?e=XQfYnb

**Comment by FlorianBorn71** [comment]
Hi, to clarify, this ticket is about proper orientation/navigation, not about the checkerboard pattern that kicks in as soon as the model is visible?
The checkerboard appears when the model has >20M points so that does not seem to be in line with your <10M point assumption. If you can post a conversion Id (or a session Id for rendering) here, we could have a look into telemetry to look at some model stats.

**Comment by jakrams** [comment]
@travis-rothbloom the checkboard pattern appears when the limit of the number of rendered points is exceeded. The easiest way to get around this, is to boot up a Premium VM, which does have more computational power and thus no limit on the number of points. You can boot up such a VM for just a few minutes to check whether your model works there.

If it works there and you are certain that your model has less than 10 million points, we can take a look at why the rendering server thinks the limit has been exceeded.

**Comment by travis-rothbloom** [comment]
Thanks both for the quick reply. I need to confirm later the number of points, but just to ask- is the 20m limit just for ARRT and not remote rendering as a whole? The documentation here says billions of points are allowed, and really the whole purpose of this is to be able to render without worrying about limits of possible: https://learn.microsoft.com/en-us/azure/remote-rendering/overview/features/point-cloud-rendering

**Comment by jakrams** [comment]
The limit is for Standard VMs. Premium VMs have no limit. ARRT doesn't expose any additional limits either.

**Comment by jakrams** [comment]
All you need to do, is to select "Premium" when you start a session:

![image](https://user-images.githubusercontent.com/36191331/196344524-e5fad6e8-b32d-4344-96e7-eaa57b2bc0d0.png)

**Comment by travis-rothbloom** [comment]
Thank you Jan, that answers my question and I can confirm I can view larger datasets now. This issue can be closed, but I do recommend that the documentation/UI be updated to make it more clear what this "Size" option in the Rendering Session dialogue corresponds to.
