### ISSUE TITLE
Critical: Connection to ARR rendering session failed: VideoFormatNotAvailable (retrying)

### ISSUE THREAD

**Issue by jelmerS2** [Azure/azure-remote-rendering-asset-tool#159]
I'm running the tool via Parallels on a Mac M2. 
When starting an ARR session, the console shows repeatedly:

- Info: New connection state: "Session Ready" [00:00:05.749]
- Info: New connection state: "Runtime Connecting" [00:00:00.000]
- Critical: Connection to ARR rendering session failed: **VideoFormatNotAvailable**
What could this VideoFormatNotAvailable mean? Is parallels missing some essential video codec? Or is this on the server's end?

**Comment by jelmerS2** [comment]
Do I have to purchase the HEVC codec?? https://apps.microsoft.com/detail/9NMZLZ57R3T7?hl=nb-no&gl=NO

**Comment by MichaelZp0** [comment]
We do not support Mac officially and actually never tested it in depth.
You could try the HEVC codec, but that would also be a longshot.
Reading up on it, Parallels adds even more layers between your app and the GPU hardware decoding, so it might be that one driver in the chain does not support the decoding and then it fails.

The error code suggests, that it is definitely a decoder issue. You might have more luck asking Parallels what type of hardware decoding they support and whether you can extend this with some settings/extensions in Parallels. For ARR you would need either H.264 or HEVC (H.265) support.
