### ISSUE TITLE
Invalid ConversionSettings.json created when modifying only some of the axes

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering-asset-tool#19]
If you modify less than 3 axis in the convert configuration window it produces and invalid configuration.

![image](https://user-images.githubusercontent.com/1579290/86354696-c91e1000-bc69-11ea-817c-800c34f9f023.png)

The error message returned is 
"InvalidConversionRequest: ConversionProcessFailed - Invalid input provided. Check logs in output container for details."

Looking at the configuration uploaded it shows "Default" for the non-adjusted axis. Which doesn't look like it's supported based on the documentation..

`{
    "axis": [
        "Default",
        "+z",
        "-y"
    ],
    "generateCollisionMesh": false,
    "sceneGraphMode": "static"
}
`

**Comment by mafranc** [comment]
Thanks for reporting the issue!
Yes I'm aware of the problem. The fix is very simple. I'll submit it later today. If you are working with the binaries you will have to wait until the next release (probably Monday)

**Comment by WikkidEdd** [comment]
Great, I'm not intensively using it so I can wait. I just spotted it and thought I'd report it :)
