### ISSUE TITLE
[Feature Request] Renderer center model initially and Far Clipping Plane settings

### ISSUE THREAD

**Issue by reneschulte** [Azure/azure-remote-rendering-asset-tool#31]
Great app which is super useful. 

It would be good to have a mode in the Renderer where it computes the Bounding Box of the geometry and centers it by default or something similar that ensures one can see the model initially. I run into it sometimes where I could not see anything rendered but that was just because the geometry was behind the far clipping plane. 

Also an option would be good to change the near and far clipping similar like the frustum FoV setting.

**Comment by mafranc** [comment]
Hi Rene, thanks for the feedback.
This feature is pretty high in our backlog, so hopefully it will be done soon.

This problem usually arises when the scale of the model is too big or too small. So another solution will be to have a global scaling parameter (which can also be computed automatically given the bounding box). I would expect this would fix the problem more intuitively, without having to change proportionally near/far plane and camera speed each time you load a model with an unusual scaling.

**Comment by reneschulte** [comment]
Yep, sounds even better,
