### ISSUE TITLE
Improve upload feedback

### ISSUE THREAD

**Issue by Merichbier** [Azure/azure-remote-rendering-asset-tool#72]
Currently while uploading files, we can only see how many files have been uploaded so far. It would be good to see the progress of each files. Examples while uploading a large file (~500 MB) we can't see the progress of the upload. It would be good to see the percentage of the upload / time remaining etc.

**Comment by mafranc** [comment]
It is indeed a known issue, we should be able to calculate a proper upload percentage. We'll work on the fix, thanks a lot for the feedback!

**Comment by ChristopherManthei** [comment]
Unfortunately, we rely on the [Microsoft Azure Storage Client Library for C++](https://azure.github.io/azure-storage-cpp/index.html) which right now does not support progress reporting for single files: [Feature request: Add support for upload / download progress reporting](https://github.com/Azure/azure-storage-cpp/issues/407). So until that feature is added we can't easily add it to ARRT.

**Comment by jakrams** [comment]
This feature has finally been added in [ARRT 2.1.0](https://github.com/Azure/azure-remote-rendering-asset-tool/releases/tag/v2.1.0) :)
