### ISSUE TITLE
Arrt tool vanishing when rendering object

### ISSUE THREAD

**Issue by parance** [Azure/azure-remote-rendering-asset-tool#76]
In the last few weeks i`ve noticed when the Arrt tool is rendering (regardless of model used)  it will run fine with keyboard functions (WASD) and the auto-collecting statistics but as soon as I click with the mouse pointer in the render view the tool crashes. 
It ran fine previously. 

Any ideas what could be causing this?
Thanks

**Comment by mafranc** [comment]
Thanks for reporting the problem!

I suggest you delete the local configuration file, in case there is some invalid value that is used during mouse navigation. 
- Close ARRT, if it's running.
- Find the configuration file here %LOCALAPPDATA%/Arrt/config.json
- Rename the file, as a backup
- Start ARRT
- Insert again your credentials details for Azure Remote Rendering and Azure Storage
- Try and repro

Let me know if this doesn't fix it, so we can try a different approach.
Marco

**Comment by parance** [comment]
Hi Marco,
Just tried your suggestion but again same issue.

I`ll try and give it a go on another PC in case something on mine has changed.

**Comment by parance** [comment]
I tried on another PC with a fresh install and had the same issue, but then i realised its the left mouse button thats causing the crash, the right mouse button is ok. Click the left mouse in the 3d viewport and it vanishes.

**Comment by mafranc** [comment]
I could repro.
Apparently it crashes only when you click on the empty space (not on an object).
We'll work on a fix as soon as possible.

Marco

**Comment by mafranc** [comment]
Can you try with the new version 1.6? That should be fixed!

Best regards,
Marco

**Comment by parance** [comment]
All good now with 1.6, thanks Marco.
